# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-15 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.CharField(default='', max_length=200),
        ),
    ]
