# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-16 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190415_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(blank=True, max_length=300, verbose_name='\u6458\u8981'),
        ),
    ]
