# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-16 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
