# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-16 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190416_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
