# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-17 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190417_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
