# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-18 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
