# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-18 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_article_views_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(blank=True, max_length=300, verbose_name='\u6458\u8981'),
        ),
    ]
